version: '3'

services:
  db:
    image: bitnami/postgresql
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker 
      - POSTGRESSQL_DATABASE=docker
    restart: always